// Pre-built demo account data for presentations and testing

export const DEMO_EMAIL = 'demo@wealthsense.in';
export const DEMO_PASSWORD = 'Demo@2026';

export const DEMO_FD_BOOKINGS = [
  {
    fd_id: 'suryoday-sfb-12m',
    bank_name: 'Suryoday Small Finance Bank',
    bank_type: 'SmallFinance',
    amount: 100000,
    gross_rate: 8.50,
    tenor_months: 12,
    booking_date: '2025-06-01',
    maturity_date: '2026-06-01',
    maturity_amount: 108500,
    net_maturity_amount: 106350,
    dicgc_insured: true,
    status: 'ACTIVE',
    name: 'Demo User',
    phone: '9876543210',
  },
  {
    fd_id: 'hdfc-bank-6m',
    bank_name: 'HDFC Bank',
    bank_type: 'Private',
    amount: 100000,
    gross_rate: 7.00,
    tenor_months: 6,
    booking_date: '2026-03-01',
    maturity_date: '2026-09-01',
    maturity_amount: 103500,
    net_maturity_amount: 102800,
    dicgc_insured: true,
    status: 'ACTIVE',
    name: 'Demo User',
    phone: '9876543210',
  },
  {
    fd_id: 'jana-sfb-18m',
    bank_name: 'Jana Small Finance Bank',
    bank_type: 'SmallFinance',
    amount: 100000,
    gross_rate: 8.25,
    tenor_months: 18,
    booking_date: '2025-09-15',
    maturity_date: '2027-03-15',
    maturity_amount: 112375,
    net_maturity_amount: 110200,
    dicgc_insured: true,
    status: 'ACTIVE',
    name: 'Demo User',
    phone: '9876543210',
  },
];

export const DEMO_MF_HOLDINGS = [
  {
    fund_id: 'mirae-lc-reg',
    fund_name: 'Mirae Asset Large Cap',
    amc_name: 'Mirae Asset',
    category: 'Large Cap',
    variant: 'Regular',
    invested_amount: 150000,
    holding_period_months: 18,
    expense_ratio: 1.52,
    annual_saving: 1470,
    saving_10y: 21800,
  },
  {
    fund_id: 'hdfc-fc-reg',
    fund_name: 'HDFC Flexi Cap',
    amc_name: 'HDFC Mutual Fund',
    category: 'Flexi Cap',
    variant: 'Regular',
    invested_amount: 100000,
    holding_period_months: 6,
    expense_ratio: 1.68,
    annual_saving: 900,
    saving_10y: 18810,
  },
  {
    fund_id: 'sbi-nifty-reg',
    fund_name: 'SBI Nifty 50 Index',
    amc_name: 'SBI Mutual Fund',
    category: 'Index Fund',
    variant: 'Regular',
    invested_amount: 75000,
    holding_period_months: 36,
    expense_ratio: 0.50,
    annual_saving: 225,
    saving_10y: 3200,
  },
];

export const DEMO_GOALS = [
  {
    goal_type: 'house',
    goal_emoji: '🏠',
    goal_title: 'Home Down Payment',
    target_amount: 2000000,
    target_date: '2031-04-01',
    existing_savings: 350000,
    monthly_sip: 18500,
    recommended_return: 12,
    instrument_recommendation: 'Equity MF',
  },
  {
    goal_type: 'emergency',
    goal_emoji: '🆘',
    goal_title: 'Emergency Fund',
    target_amount: 300000,
    target_date: '2026-12-01',
    existing_savings: 150000,
    monthly_sip: 25000,
    recommended_return: 7,
    instrument_recommendation: 'FD',
  },
];
